AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket with the name 'infrabucket030226'

Resources:
  infrabucket030226:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: infrabucket030226