AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket, SNS topic, SNS topic policy, Lambda function, IAM role, SNS subscription and Lambda permission

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucketinfrabotsopra29
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:*
            Topic: !Ref SNSTopic

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: EventsTopicinfrabotsopra29

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SNSTopic
      Topics:
        - !Ref SNSTopic

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lambdainfrabotsopra29
      Runtime: python3.9
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            print(event)
            return {
                'statusCode': 200,
                'body': 'Lambda function executed successfully'
            }
      Handler: index.lambda_handler
      Role: !GetAtt LambdaRole.Arn

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: lambda
      Endpoint: !GetAtt LambdaFunction.Arn

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref SNSTopic

Outputs:

  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketName"

  SNSTopicName:
    Description: SNS Topic Name
    Value: !Ref SNSTopic
    Export:
      Name: !Sub "${AWS::StackName}-SNSTopicName"

  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionName"