AWSTemplateFormatVersion: '2010-09-09'
Description: Create a DynamoDB table with name testtable

Resources:
  testtable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: testtable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5