AWSTemplateFormatVersion: '2010-09-09'
Description: Create a DynamoDB table named "EmployeeTable"

Resources:

  EmployeeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5